### ISSUE TITLE
Whacky login

### ISSUE THREAD

**Issue by nmaier** [downthemall/website#28]
The personas login is kinda whacky sometimes.

When I signed in the first time, I got a sign-in notification (correct), but when I navigated, it signed in again with another notification (incorrect, already signed in)?

When I signed out, navigated and signed in again, it displayed a signed-out notification (incorrect, not signed in) and afterwards a sign-in notification (correct).

**Comment by nmaier** [comment]
The sign out/sign in dance also happens when navigating during a session

**Comment by stefanoverna** [comment]
You're right, but it's quite randomic so far. Did you find a deterministic way to reproduce it? Thanks

**Comment by nmaier** [comment]
I tried for a couple of minutes, observed this a lot, but not in a deterministic way
