### ISSUE TITLE
KB: Content text area too small

### ISSUE THREAD

**Issue by nmaier** [downthemall/website#30]
The Content textarea/editor is too small and almost not selectable.
Also, once I finally managed to select it and type (seems there is also no tabstop there) the prefix/full screen icons where only partially visible, truncated on the  top.

**Comment by stefanoverna** [comment]
Screenshot please? :smile: On which browser are you experiencing this? Works fine here.

**Comment by nmaier** [comment]
Nightly, Build identifier: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:23.0) Gecko/20130408 Firefox/23.0
![After loading page](https://f.cloud.github.com/assets/383665/354210/244c74bc-a098-11e2-89d1-281b5513b0c3.png)
After loading page

![After painstakingly selecting the area and typing something](https://f.cloud.github.com/assets/383665/354211/36b9d194-a098-11e2-950e-3490b9c7e690.png)
After painstakingly selecting the area and typing something

**Comment by nmaier** [comment]
Same with clean profile and Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:20.0) Gecko/20100101 Firefox/20.0

**Comment by nmaier** [comment]
I force-refreshed the site as well, to prevent any cached items messing something up, if this was your next question ;)

**Comment by stefanoverna** [comment]
Ok, thanks :)
