### ISSUE TITLE
State OS/browser support on homepage

### ISSUE THREAD

**Issue by nmaier** [downthemall/website#35]
We want users to actually click the Install links, so better state DownThemAll! is compatible with their system.
Either display a full list, or detect the sys/browser and display that.

Having some unobtrusive gfx, like OS/Browser logos might help

**Comment by stefanoverna** [comment]
9cf8e9805fe042af81efffb9191dfe02fd7b4632 is able to detect browsers/os. Right now we just hide the install button if the browser is not Firefox. We also show that DTA is available on all the platforms.

![34](https://f.cloud.github.com/assets/51573/376812/56126c26-a459-11e2-8772-b0b1fa73144a.png)
