### ISSUE TITLE
Comments on news

### ISSUE THREAD

**Issue by namuit** [downthemall/website#38]
I would add Disqus as comment platform in the news (like https://test.downthemall.net/it/news/1 ).

**Comment by stefanoverna** [comment]
I agree on this, but I remember @nmaier was against the use of a 3rd party commenting system. IMHO, comments done the right way® are not trivial (think about threads, moderation, spam filtering, notifications, etc): and we don't have the time or interest to implement this from scratch.

I also know https://github.com/phusion/juvia, a Rails clone of Disqus/IntenseDebate. Let's debate :)

**Comment by stefanoverna** [comment]
Disqus could be a new form of income too: http://disqus.com/audience/

**Comment by nmaier** [comment]
I'm not really in favor of comments at all, as for such software projects it's usually just a mixture of "thanks" and (misguided) bug reports. If we wrote actual comment-worthy stuff that would be a different matter.

**Comment by stefanoverna** [comment]
Closing for now
