### ISSUE TITLE
OpenID signup/login support

### ISSUE THREAD

**Issue by nmaier** [downthemall/website#6]
E.g. https://github.com/nbudin/devise_openid_authenticatable

**Comment by stefanoverna** [comment]
Do we really need this?

**Comment by nmaier** [comment]
Yep. Registration stuff is always a major barrier, and at least from my experience openid enabled registration/auth made me a lot less frustrated many times

**Comment by stefanoverna** [comment]
Well, in #9 you say most users will never want to log in, which I totally agree. So I guess that's not an high priority item. I'd say the small percentage of interested users will log in with a normal signup procedure, at least in the first phase.

**Comment by stefanoverna** [comment]
Thinking more about it I'd like to avoid the creation of an internal authentication system. Right know I've implemented a simple email-based sign-up sistem, but I'd like to remove it: too much burden and security involved.

Far better would be to just use an external system, wether it's Mozilla Persona, Facebook, Twitter, Github, Google or any other. What do you thing @downthemall/owners ?

**Comment by JimmY2K** [comment]
Fine for me. I'd give choice between Persona, Twitter and Google .

**Comment by nmaier** [comment]
We're a mozilla shop, kinda, so Persona likely makes most sense, and is in theory also not locked-in.
Other than this I don't really like vendor lock-in, so OpenID would be most appropriate.

**Comment by nmaier** [comment]
Oh, and no facebook please, or else I won't be able to login at all :p

**Comment by stefanoverna** [comment]
I've implemented Persona integration.
